# Python Assignment #3  for iNeuron

### 1- Write a function to compute 5/0 and use try/except to catch the exceptions.

In [35]:
def myDivFun(num,deno):
    
    try:
        if deno == 0:
            raise ArithmeticError()
        else:
            print( 'Division Value = ', (num/deno) )
    
    except( ArithmeticError ):
        if ZeroDivisionError:
            print( 'ZeroDivisionError - You cannot divide any number by Zero')
        else:
            print( ArithmeticError.with_traceback() )
    
    finally:
        print( 'End of my Function!!' )

print( ' ==-- Error Function Call --== ')
myDivFun(5,0)
print( '\n ==--  Normal Function Call --== ')
myDivFun(12,4)

 ==-- Error Function Call --== 
ZeroDivisionError - You cannot divide any number by Zero
End of my Function!!

 ==--  Normal Function Call --== 
Division Value =  3.0
End of my Function!!


### 2- Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [19]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

# for i in range(2):
#     for j in range(2):
#         for k in range(2):
#             print( subjects[i] + ' ' + verbs[j] + ' ' + objects[k] )

# comb_list = [ subjects[i] + ' ' + verbs[j] + ' ' + objects[k]  for i in range(2) for j in range(2) for k in range(2) ]
# for i in comb_list:
#     print( i )
    
print( '\n'.join( [ subjects[i] + ' ' + verbs[j] + ' ' + objects[k]  for i in range(2) for j in range(2) for k in range(2) ] ) )

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


### 3 - Write a function so that the columns of the output matrix are powers of the input vector. 
- The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [1]:
import numpy as np

In [55]:
# oneArray = np.ones(4, dtype=np.int8).reshape( 4,1 )
# # myMat = np.array(  ).reshape(len(myList),1)
# # myMat
# # listArr = np.array( [3,5,2,10], dtype=np.int8 ).reshape( 4,1 )
# # listArr
# listArr = np.array( [3,5,2,10] ).reshape( 4,1 )
# combArr = np.concatenate( (oneArray,listArr,listArr**2,listArr**3), axis=1 )
# np.flip( combArr, axis=1 )
# # oneArray
# # listArr

In [56]:
# myMat = np.array( [3,5,2,10] )
# print( 'Basic Matrix :', myMat )
# vanderMat = np.vander( myMat )
# print( 'Vander Matrix : \n', vanderMat )

In [89]:
baseList = [3,5,2,10]

# Arithmatic Way
baseArray = np.array( baseList ).reshape( len(baseList), 1 )

onesArray = np.ones(len(baseList), dtype=np.int8).reshape( len(baseList), 1 )

combArray = np.concatenate( (onesArray, baseArray, baseArray**2, baseArray**3), axis=1 )

combArray = np.flip( combArr, axis=1 )

# Numpy Way
numpyMat = np.array( baseList )
vanderNumpyMat = np.vander( numpyMat )


print( 'Base List : ', baseList )
print( '\nVander Array Manual Way:' )
print( combArray )
print( '\nVander Array Numpy Way:' )
print( vanderNumpyMat )

Base List :  [3, 5, 2, 10]

Vander Array Manual Way:
[[  27    9    3    1]
 [ 125   25    5    1]
 [   8    4    2    1]
 [1000  100   10    1]]

Vander Array Numpy Way:
[[  27    9    3    1]
 [ 125   25    5    1]
 [   8    4    2    1]
 [1000  100   10    1]]


In [90]:
baseList = [7,4,10]

# Arithmatic Way
baseArr2 = np.array( baseList ).reshape( len(baseList), 1 )

onesArr2 = np.ones(len(baseList), dtype=np.int8).reshape( len(baseList), 1 )

combArr2 = np.concatenate( (onesArr2, baseArr2, baseArr2**2), axis=1 )

combArr2 = np.flip( combArr2, axis=1 )

# Numpy Way
numpyMat = np.array( baseList )
vanderNumpyMat = np.vander( numpyMat )


print( 'Base List : ', baseList )
print( '\nVander Array Manual Way:' )
print( combArr2 )
print( '\nVander Array Numpy Way:' )
print( vanderNumpyMat )

Base List :  [7, 4, 10]

Vander Array Manual Way:
[[ 49   7   1]
 [ 16   4   1]
 [100  10   1]]

Vander Array Numpy Way:
[[ 49   7   1]
 [ 16   4   1]
 [100  10   1]]
